### PR TITLE
This is a sampling of code meant to demonstrate collections for attrio.

### PR DESCRIPTION
**Pull request by anithri**
This request is meant for discussion, it is unready for merging.

I'm going to do this work, but I wanted to know what you guys thought of it.  It could also be implemented as a plugin for Attrio. 

I love the Attrio code so far, and I'm planning to use it in another project soon.  However, I need to have similar functionality for collections of objects in addition to the attributes already provided.  This outlines one way to accomplish this.

We start by modifying AttributesParser to include a #collection public method which allow you to define collections.  Each collection has 3 groups of methods.  a Reader which gives you full access to the collection.  a AddElement, which adds a new element to the array, and a FindElement which will allow you to read a single element of the collection based on an index.

Collections may be 1 of 3 types.  With no special options, Attrio::Collection will create an Array.  With a :unique options key set to true and no :index key, Attrio::Collection will create a Set.  With a :unique key set to true and an :index key, Attrio::Collection will create a hash, and will call the method defined by the :index key and use the result as the hash key.  This would allow you to do something like...

``` ruby
class ClassSection
  include Attrio
  define_attributes do
    attr :name, String
    attr :teacher, Faculty
    collection :students, Student, unique: true, index: :student_id
    collection schedule, DateTime, unique: true
    collection reading_materials, String
  end
end
```

the students collection would be a hash in this case, using the return value from student.student_id, as the key.  
The schedule collection would be a set, and the reading_materials collection would be an array.

FindElement can be used for any container, the default value defined for the collection will be returned if no element is found.

AddElement should be structured to accept an array of hashes that can be used to add a number of elements at the same time as well as adding only a single one at a time.

This code is not tested yet.

Readme changes are examples of using Collections.
attributes_parser had collection, create_collections, and
fetch_container_type methods added.
collection is a class parallel to Attribute for use with collections.

### CODE REVIEW

**Comment by igor-alexandrov** [comment]
Hello,
We reviewed a bit your code and these are our thoughts about it.
1) This is cool and should be added to Attrio
2) Implementation should be done as follows:
- we need three different classes: `Collection::Array`, `Collection::Set` and `Collection::Hash` that all should be inherited from `Array`, `Set` and `Hash` instead of passing `container` to constructor of `Collection`.
- these classes should be include module that will implement methods like `reader_visilbilty` and so on; this module should also be included into `Attribute` class.
  3) `index` option should be renamed to `key`, because it reflects what it actually is; it is a key from Hash.

**Comment by anithri** [comment]
Alright, things are getting close now.  Have a few questions though.
1.  should both attributes and collections go into the :as/attributes hash?  If not we need a different option to rename collections to.
2.  DefaultValue has 2 different meanings for collections:  1 is to use as a return value when no element is found using #find_element (Call it :not_found ?) and the other is to initialize the collection with (call it :initial_values ?)
3.  Should we put in any functionality for the following?
   -  #add_element can take a single value or an array of values.  Currently if 1 element of the array is the wrong Type, a TypeError gets raised and and #add_element is a partial success, all elements before the wrong type are added, none of the ones after are.  we could pretty easily do all the Type checks before any got added, we could also add an option to :skip_type_errors to just skip the incorrect values.  either way this adds some complexity.
   - when #add_element is used in a Hash, new elements added that use an existing index will succeed, overwriting the existing value.  Should we add a check to raise an error when :raise_on_redefine?
   -  in your builders, you use: a `unless klass.method_defined?(options[:method_name])` block, I prefer to use a guard clause like: `return if klass.method_defined?(options[:method_name])`.  But I don't want to change your style without asking.
   -  #find_element finds the first element in an Array (and the only element in a Set).  Expanding #find_element offers the chance for multiple matches and thus returning an Array of results instead of a single one.  Should there be a sear
   -  #find_element is pretty bare bones.  I like it for Hashes because it already accounts for the proper index function.  it could be easily extended to also take a hash, where the keys of the hash are methods to call for each element and the value is the value(s) you want the results of those methods to match. This makes #find_element much more useful for Sets and Hashes.  `my_obj.find_users(last_name: ['Jones','Smith','Doe'], first_name: "John")`  Maybe use a search_elements for this instead and have it always return an array.

I still need to add integration tests to test the whole thing top to bottom.

**Comment by anithri** [comment]
Ok after some more code reading and thought, this is the next set of stuff that I'm going to implement.

#### :collections_as options

`:collections_as` alias(`:c_as`) will be the option name to set the name of the collections hash, defaults to "collections"

`obj.reset_collections(collections_to_reset)` to empty all collections in the collections_to_reset array

`obj.reset_collections_initial_values(collections_to_reset)` to set collections in the collections_to_reset array to empty, and then filled with initial values

In addition, I'm going to differ from the attributes and make the collections hash a first class object, move most of the functionality for reset and initialize into the object and use dispatch to connect the instances.  If it works out, I'd say that the attributes hash could be similarly refactored.

This separation offers some nice opportunities.  They could be used as the basis of a plugin system which allows the possibility to add depth in the way classes are created, marshalled, stored, initiliaze...

#### :unfound_value option

`:unfound_value` alias(`:unfound`) will be the option that sets the return value of the find_ method when no matching element is found.  This could be used to return a null object or a default value.

#### :initial_value option

`:initial_value` alias(`:initial_values`,`:initial`) will be the option that takes the values used to initialize the collection.  This can be a single value or an array of elements to add.

**Comment by anithri** [comment]
Ok, This now contains a working implementation of collections with working and passing specs.  There are some small changes to be made, mostly to match coding styles (I tend to use the `{test: "Me"}` way of doing hashes while you use `{:test => "Me"}`). Also it's possible you have more apt names for some of these classes or methods.

I invite all comments, suggestions, changes....  Let me know what you think.

thanks!

**Comment by igor-alexandrov** [comment]
So...
I see a lot of work done here. Have you seen our light implementation of collections in Attrio? I am thinking about some combination of your approach and our.

**Pull request closed without merging**
